import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-container': '#ef9900',
        primary: '#00236f',
        'surface-bright': '#f8f9ff',
        'inverse-surface': '#213145',
        'on-secondary': '#ffffff',
        secondary: '#006591',
        tertiary: '#3e2400',
        'inverse-on-surface': '#eaf1ff',
        'outline-variant': '#c5c5d3',
        'surface-container-highest': '#d3e4fe',
        'surface-container': '#e5eeff',
        'on-tertiary-fixed': '#2a1700',
        'surface-tint': '#4059aa',
        'on-secondary-fixed': '#001e2f',
        'surface-container-low': '#eff4ff',
        'on-primary': '#ffffff',
        'inverse-primary': '#b6c4ff',
        'on-primary-container': '#90a8ff',
        'surface-container-high': '#dce9ff',
        'on-error-container': '#93000a',
        'on-surface-variant': '#444651',
        'on-primary-fixed-variant': '#264191',
        'tertiary-fixed': '#ffddb8',
        'secondary-fixed-dim': '#89ceff',
        surface: '#f8f9ff',
        outline: '#757682',
        'primary-fixed-dim': '#b6c4ff',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'tertiary-container': '#5c3800',
        'on-secondary-container': '#004666',
        'primary-fixed': '#dce1ff',
        error: '#ba1a1a',
        'on-secondary-fixed-variant': '#004c6e',
        'secondary-container': '#39b8fd',
        'surface-dim': '#cbdbf5',
        'on-tertiary-fixed-variant': '#653e00',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#0b1c30',
        background: '#f8f9ff',
        'on-background': '#0b1c30',
        'secondary-fixed': '#c9e6ff',
        'surface-variant': '#d3e4fe',
        'primary-container': '#1e3a8a',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#00164e',
        'tertiary-fixed-dim': '#ffb95f',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'section-gap': '64px',
        'margin-desktop': '40px',
        gutter: '24px',
        'stack-md': '16px',
        'stack-lg': '24px',
        'container-max': '1280px',
        'margin-mobile': '16px',
        'stack-sm': '8px',
      },
      fontFamily: {
        'label-md': ['Manrope', 'sans-serif'],
        'label-sm': ['Manrope', 'sans-serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        'headline-lg-mobile': ['Manrope', 'sans-serif'],
        'headline-lg': ['Manrope', 'sans-serif'],
        'body-md': ['Manrope', 'sans-serif'],
        'headline-md': ['Manrope', 'sans-serif'],
        display: ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        display: ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
      },
    },
  },
  plugins: [],
} satisfies Config;
