services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: ./backend
      dockerfile: WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__ReadDatabase=Host=postgres;Port=5432;Database=trip-planner;Username=postgres;Password=Password@1234
      - ConnectionStrings__WriteDatabase=Host=postgres;Port=5432;Database=trip-planner;Username=postgres;Password=Password@1234
      - Redis__Connection=redis:6379
      - MinIO__Endpoint=minio:9000
    ports:
      - "5501:8080"
    depends_on:
      - postgres
      - minio
      - redis

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: Password@1234
      POSTGRES_USER: postgres
      POSTGRES_DB: trip-planner
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "miniodata:/data"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=Password@1234
    command: server --console-address ":9001" /data

volumes:
  pgdata:
  miniodata: